# Generated by Django 6.1.1 on 2026-10-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='contacts.contactstatus'),
        ),
    ]
