# Generated by Django 6.1.1 on 2026-10-07 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Enter 9 to 15 digits, optionally starting with +', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
